module.exports = {
    USER_DOES_NOT_EXIST: 'User not found',
    USER_ALREADY_EXIST: 'User already exist',
    WRONG_PASSWORD: 'Incorrect password',
    BAD_EMAIL: 'Bad email address',
    BAD_TOKEN: 'Authentication failed. Sign in or create an account',
    BAD_EMAIL: 'Bad email address',
    INVALID_KEY: `The provided key in invalid. Kindly request for a key if you don't have one`,
    NO_KEY_ASSIGNED: `No key has been assigned to this seller account. If you have a key, kindly register with a new email address`,
    KEY_IS_REGISTERED: 'The provided key has been registered already. Please sign in instead',
    DUPLICATE_INVITATION_KEY: 'This key already exist',
    JSON_WEB_TOKEN_ERROR: 'Json web token failed',
    USED_KEY: 'The provided key has been used',
    PRODUCT_ALREADY_IN_CART: 'Product is already in cart. Visit cart to increase quantity if needed',
    PRODUCT_NOT_AVAILABLE: 'This product is not available. Why not buy something else',
    PRODUCT_OUT_OF_STOCK: 'This product is out of stock',
    PRODUCT_DOES_NOT_EXIST: 'This product does not exist',
    USER_CART_NOT_FOUND: 'User cart was not found',
    FAILED_TO_FIND_CART_ITEM: 'Failed to find item in cart',
    CARD_ALREADY_ADDED: 'You have added this card already',
    CARD_NOT_FOUND: 'Card not found',
    FAILED_TO_FETCH_CARD: 'Error fetching cards',
}